### ISSUE TITLE
feat: `abcd_demo` converts values of `company_name` to title case, to match AR data

### ISSUE THREAD

**Issue by vintented** [RMI-PACTA/r2dii.data#207]
Currently, all companies names in the `ald` and `ald_demo` are in lower case (E.g., Total Sa becomes total sa). In all other AR datasets, companies are in title case. We would like to try and keep the company names consistent across datasets. 

Likewise, if a bank used a non-AR `ald` dataset, the company names possibly could be in title case. I am happy to provide a sample `ald` file with the title case company names. Let me know if I can clarify anything further? 

[AB#10169](https://dev.azure.com/RMI-PACTA/d77fc8f8-abac-42ae-9e31-846f9901290d/_workitems/edit/10169)

**Comment by maurolepore** [comment]
I agree consistency is desirable. I would achieve it programatically rather than in a hard-coded way.

``` r
library(stringr)
str_to_title("company name")
#> [1] "Company Name"
```

<sup>Created on 2021-02-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

This way we could keep the best of both worlds: Write low-level (developer-facing) programs that expect the simpler, lowercase names, then help users format the output in a way consistent with AR and other data providers. What I propose is to export a tiny helper, say `format_company_name()` that produces the title case format you want. 

@jdhoffa, what do you think?

**Comment by jdhoffa** [comment]
Hmmm. I think this is a little tricky.
On the one hand `ald_demo` is meant to best reflect the data coming from AR "as-is". Meaning if they will be providing the data in title case, we should try to provide the demo data best reflecting this. 

On the other hand, of course lowercase is always easier to deal with from the code, and this is what is expected in all other functions etc. That said, it would be easy (and maybe safer) to just add a line in `r2dii.match` and `r2dii.analysis` that forces all input data to lowercase.

Perhaps that is the best solution?

**Comment by maurolepore** [comment]
Sounds great. If I understand correctly, here is the current situation the user story, and proposed solution:


* Current situation:

```r
head(unique(r2dii.data::ald_demo$name_company))
#> [1] "aba hydropower generation co ltd" "achinsky glinoziemskij kombinat" 
#> [3] "affinity renewables inc."         "africa oil corp"                 
#> [5] "africon shipping sa"              "agni steels private limited"
```

* User stories:

As a user of r2dii.data I would like to have an `ald_demo` dataset where `company_name` has title case values so that its letter case is identical to the data I get from AR.

As a user of r2dii packages downstream from r2dii.data I would like to have functions that automatically deal with the letter case of the column `company_name` so I do not need to worry about that myself.

* Solutions

    1. In `r2dii.data::ald_demo$company_name` convert to title case.
    2. In all packages downstream to r2dii.data, convert `ald_demo::company_name` to lowercase.`^[*]`

`[*]:` This doesn't scale well. Do we have more of such "sanitizion" issues? Maybe we need an intermediate package-layer just after r2dii.data that sanitized data from a specific provider like AR?
