### ISSUE TITLE
nace_classification has duplicate values

### ISSUE THREAD

**Issue by KapitanKombajn** [RMI-PACTA/r2dii.data#229]
Hi,
it's rather a minor issue, but nace_classification dataset has duplicate values in the code field. As a result same code may be mapped to different sectors.  

```r
library(dplyr)

#code duplicates
r2dii.data::nace_classification %>% dplyr::count(code) %>% filter(n>1)
```

**Comment by maurolepore** [comment]
Thanks @KapitanKombajn!

--

Multiple `original_code` values map to a single `code`. @jdhoffa, is this expected?

``` r
library(dplyr, warn.conflicts = FALSE)

data <- r2dii.data::nace_classification

# If you consider all columns, the data is unique
identical(nrow(data), unique(nrow(data)))
#> [1] TRUE

But the suspected 'duplication' comes because multiple `original_code` values map to a single `code`.
data %>% 
  add_count(code) %>% 
  filter(n > 1)
#> # A tibble: 38 x 6
#>    original_code code  code_level sector       borderline     n
#>    <chr>         <chr>      <dbl> <chr>        <lgl>      <int>
#>  1 1             10             2 not in scope FALSE          2
#>  2 1.1           110            3 not in scope FALSE          2
#>  3 1.2           120            3 not in scope FALSE          2
#>  4 1.42          1420           4 not in scope FALSE          2
#>  5 1.61          1610           4 not in scope FALSE          2
#>  6 2             20             2 not in scope FALSE          2
#>  7 3             30             2 not in scope FALSE          2
#>  8 3.1           310            3 not in scope FALSE          2
#>  9 3.22          3220           4 not in scope FALSE          2
#> 10 5             50             2 coal         FALSE          2
#> # … with 28 more rows

data %>% 
  add_count(code, original_code) %>% 
  filter(n > 1)
#> # A tibble: 0 x 6
#> # … with 6 variables: original_code <chr>, code <chr>, code_level <dbl>,
#> #   sector <chr>, borderline <lgl>, n <int>

# Another view
data %>% 
  add_count(code) %>% 
  mutate(duplicated_code = duplicated(.data$code)) %>% 
  arrange(desc(n), code) %>% 
  relocate(code, original_code, n, duplicated_code, .after = borderline)
#> # A tibble: 996 x 7
#>    code_level sector       borderline code  original_code     n duplicated_code
#>         <dbl> <chr>        <lgl>      <chr> <chr>         <int> <lgl>          
#>  1          2 not in scope FALSE      10    1                 2 FALSE          
#>  2          2 not in scope FALSE      10    10                2 TRUE           
#>  3          3 not in scope FALSE      110   1.1               2 FALSE          
#>  4          3 not in scope FALSE      110   11                2 TRUE           
#>  5          3 not in scope FALSE      120   1.2               2 FALSE          
#>  6          3 not in scope FALSE      120   12                2 TRUE           
#>  7          4 not in scope FALSE      1420  1.42              2 FALSE          
#>  8          4 not in scope FALSE      1420  14.2              2 TRUE           
#>  9          4 not in scope FALSE      1610  1.61              2 FALSE          
#> 10          4 not in scope FALSE      1610  16.1              2 TRUE           
#> # … with 986 more rows
```

<sup>Created on 2021-05-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by jdhoffa** [comment]
This turns out to be a bit of an issue in how we handle both the `isic_classification` and `nace_classification` files. In particular, the less granular levels. 

Notice [here](https://unstats.un.org/unsd/classifications/Econ/Download/In%20Text/ISIC_Rev_4_english_structure.Txt), in the original ISIC Rev 4 file, how they include leading zeroes in each of the codes to distinguish level, I think this is something we should look into doing as well in our bridges. 

In the reprex below, we see that the code "50" can map to both "coal" and "shipping", which does not make sense. If we align to what is shown in the link above, "coal" would be denoted by the string "05" and "shipping" by the string "50". 

@maurolepore please review this when you have a moment and let me know what you think, it may have implications on downstream dependencies (in particular regression tests). 

@georgeharris2deg please let me know if you agree that we should move towards what is suggested above.

``` r
library(dplyr, warn.conflicts = FALSE)

data <- r2dii.data::nace_classification

data %>% 
  add_count(code) %>% 
  mutate(duplicated_code = duplicated(.data$code)) %>% 
  arrange(desc(n), code) %>% 
  relocate(code, original_code, n, duplicated_code, .after = borderline) %>% 
  dplyr::filter(sector != "not in scope") %>% 
  head()
#> # A tibble: 6 x 7
#>   code_level sector      borderline code  original_code     n duplicated_code
#>        <dbl> <chr>       <lgl>      <chr> <chr>         <int> <lgl>          
#> 1          2 coal        FALSE      50    5                 2 FALSE          
#> 2          2 shipping    FALSE      50    50                2 TRUE           
#> 3          2 oil and gas FALSE      60    6                 2 FALSE          
#> 4          3 oil and gas FALSE      620   6.2               2 FALSE          
#> 5          3 oil and gas TRUE       910   9.1               2 FALSE          
#> 6          3 cement      FALSE      235   23.5              1 FALSE
```

<sup>Created on 2021-06-10 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by maurolepore** [comment]
Thanks! So, we expect the literal string "05" but instead we have "5", right? 
I see not PR linked to this. What do you mean by review?

**Comment by jdhoffa** [comment]
We do not expect the literal string "05" necessarily! My proposal is that we should START to expect this as a solution to the bug exposed above. 

By review, I mean to say, do you think what I suggest above is a suitable solution? 
In particular, since banks are often using excel to format loanbooks prior to analysis, I wonder if they will have a difficult time setting sector classifications to these literal strings with leading 0s, and if they risk incorrect sector matches as a result. 

Let me know if this is clear or if I should provide more context.

**Comment by maurolepore** [comment]
Sorry for my poor use of verb tense. Where I said ...
> we expect the literal string "05" but instead we have "5" 
... I mean to write a user story like this one

As someone who wants to match codes following as documented [here](https://unstats.un.org/unsd/classifications/Econ/Download/In%20Text/ISIC_Rev_4_english_structure.Txt)
