### ISSUE TITLE
breaking change: consider dropping the `borderline` column

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/r2dii.data#346]
I'm not sure if any of our users every really use or even understand this column?
@jacobvjk thoughts? 

Obviously requires consideration by George as well

**Comment by jacobvjk** [comment]
With sufficient guidance people do seem to understand it and I think it is helpful in getting more reasonable match success rates. If we removed this, we would have to count all borderline loans as potential matches, which lowers the rate and does not reflect what would realistically be in scope. So I would tend to improve documentation, rather than removing the column. But we can still check with George.

**Comment by jdhoffa** [comment]
All good, I'm happy to close this issue then with that perspective! No need to think about it too much
